version: '3.4'
services:
  dmp-frontend:
    container_name: dmp-frontend
    build:
      context: .
      args:
        MODE: development
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - "8000:80"
      - "8080:8080"
