server {
  listen 8080;

  root /usr/share/nginx/html;
  index index.html;

  location /lajiapi/person {
    proxy_pass ${LAJI_API_HOSTNAME}/person;
    proxy_set_header Authorization "Bearer ${LAJI_ACCESS_TOKEN}";
    proxy_pass_request_headers on;
  }

  location /lajiapi/authentication-event {
    proxy_pass ${LAJI_API_HOSTNAME}/authentication-event;
    proxy_set_header Authorization "Bearer ${LAJI_ACCESS_TOKEN}";
    proxy_pass_request_headers on;
  }

  location /lajiapi/organizations {
    proxy_pass ${LAJI_API_HOSTNAME}/organizations;
    proxy_set_header Authorization "Bearer ${LAJI_ACCESS_TOKEN}";
    proxy_pass_request_headers on;
  }

  location / {
    try_files $uri /index.html;
  }
}